version: "3"
services:
  db:
    build:
      context: ..
      dockerfile: ./docker/db/Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ../docker/db/data:/var/lib/mysql
      - ../docker/db/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    networks:
      - db-network
networks:
  db-network:
    external: true
