version: "3"
services:
  proxy:
    build:
      context: ..
      dockerfile: ./docker/proxy/Dockerfile
    volumes:
      - ../docker/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ../docker/proxy/log:/var/log/nginx
    ports:
      - 80:80
    networks:
      - proxy-network
networks:
  proxy-network:
    external: true
