version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    # depends_on:
    #   - db
    volumes:
      - ../docker/app/src/app:/var/www/html/app
      - ../docker/app/log:/var/log/apache2
    working_dir: /var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - db-network
      - proxy-network
networks:
  proxy-network:
    external: true
  db-network:
    external: true
